name: Deploy to Github Pages

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Cache Hugo resources
              uses: actions/cache@v3
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v4
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
               
            - name: Publish
            env:
                USER: jk1ash
                EMAIL: wjj@jklash.com
                GH_REF: github.com/jk1ash/jk1ash.github.io.git
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
            run: |
                cd public
                git config --global user.name "$USER"
                git config --global user.email "$EMAIL"
                export TZ='Asia/Shanghai'
                git add .
                git commit --allow-empty -m "Auto Update: `date +'%Y-%m-%d %H:%M:%S'`"
                git push "https://$USER:$GH_TOKEN@$GH_REF" master:master
